<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_UniversalSafety" Id="{f0e14f3d-9095-4bfd-896b-69835645aeb2}" SpecialFunc="None">
    <Declaration><![CDATA[(* 
:Description: This function block is base for of machine safety module in all projects.
*)
FUNCTION_BLOCK ABSTRACT FB_UniversalSafety IMPLEMENTS I_UniversalSafety
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	bInit		: BOOL;
	bAbort		: BOOL;
	bReset		: BOOL;
	
	bError 		: BOOL;
	iErrorID 	: UDINT;
END_VAR
(*
Version history:

+-------------+------------+----------------+----------+------------------------------------------+
|Date         | Version    | created under  | Author   | Remark                                   |
+=============+============+================+==========+==========================================+
|2022-02      | 1.0.0.0    | V3.1.4024.22   | ADBO     | Function block created                   |
+-------------+------------+----------------+----------+------------------------------------------+

*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Folder Name="FirstCycle" Id="{d3c1ccb8-a820-4e21-a977-699125aaf1c2}" />
    <Folder Name="Requests" Id="{208f2369-ac3b-4f4b-aacf-43d7402d5ba7}" />
    <Folder Name="StateMachine" Id="{0ce4ea82-b385-4f7e-ab23-75422087eccf}" />
    <Method Name="MR_Abort" Id="{7737e323-79c6-41f8-9666-2e623edcbadc}" FolderPath="Requests\">
      <Declaration><![CDATA[METHOD MR_Abort : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="MR_FirstCycle" Id="{79bfae83-7fd8-4d25-a91f-80c293c99867}" FolderPath="FirstCycle\">
      <Declaration><![CDATA[METHOD MR_FirstCycle : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="MR_Init" Id="{01c722d3-cff9-4c0c-83a1-d984d6ac026a}" FolderPath="Requests\">
      <Declaration><![CDATA[METHOD MR_Init : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="MR_Reset" Id="{5a2c9cd4-cd2c-4d09-a833-16f5f5e1e7d9}" FolderPath="StateMachine\">
      <Declaration><![CDATA[METHOD MR_Reset : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="MS_Initializing" Id="{28ed100b-9dfb-4c5d-963e-f1ee5a3510a1}" FolderPath="StateMachine\">
      <Declaration><![CDATA[METHOD PROTECTED ABSTRACT MS_Initializing
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="MS_ReadyInitialized" Id="{72e42245-9163-470d-a58e-44548bd92b73}" FolderPath="StateMachine\">
      <Declaration><![CDATA[METHOD PROTECTED ABSTRACT MS_ReadyInitialized
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="MS_Reset" Id="{fb81522b-7250-4a7b-a0c2-08a6b883bca1}" FolderPath="StateMachine\">
      <Declaration><![CDATA[METHOD PROTECTED ABSTRACT MS_Reset
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="MS_ResetDone" Id="{8c8eef8d-bc9d-4bff-a492-f79612c9262a}" FolderPath="StateMachine\">
      <Declaration><![CDATA[METHOD PROTECTED ABSTRACT MS_ResetDone
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="MS_Running" Id="{af5b7f84-7b5b-4f83-9337-60081b991cf8}" FolderPath="StateMachine\">
      <Declaration><![CDATA[METHOD PROTECTED ABSTRACT MS_Running
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[;]]></ST>
      </Implementation>
    </Method>
    <Method Name="MS_Uninitialized" Id="{5a2c8241-cc5c-4e81-af52-d2a08033c045}" FolderPath="StateMachine\">
      <Declaration><![CDATA[METHOD PROTECTED ABSTRACT MS_Uninitialized
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="StateMachine" Id="{fcc9599a-6858-4fd8-9f87-385194265d55}" FolderPath="StateMachine\">
      <Declaration><![CDATA[METHOD PROTECTED StateMachine
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_UniversalSafety">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_UniversalSafety.MR_Abort">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_UniversalSafety.MR_FirstCycle">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_UniversalSafety.MR_Init">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_UniversalSafety.MR_Reset">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_UniversalSafety.MS_Initializing">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_UniversalSafety.MS_ReadyInitialized">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_UniversalSafety.MS_Reset">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_UniversalSafety.MS_ResetDone">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_UniversalSafety.MS_Running">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_UniversalSafety.MS_Uninitialized">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_UniversalSafety.StateMachine">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>