<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="F_CubitCalculate" Id="{b1c0162c-5c4b-45b0-a476-ed5b15f8ca38}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_CubitCalculate : lreal
VAR_INPUT
	A : LREAL;
	B : LREAL;
	C : LREAL;
	D : LREAL;
	x : LREAL;
END_VAR
VAR_OUTPUT
	Y : LREAL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Y := A*x*x*x + B*x*x + C*x + D;
F_CubitCalculate := Y;]]></ST>
    </Implementation>
    <LineIds Name="F_CubitCalculate">
      <LineId Id="25" Count="0" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>