<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="F_QuanDraticCalculate" Id="{0db2da43-9916-4115-ac6b-83dcb8b325cc}" SpecialFunc="None">
    <Declaration><![CDATA[// Return Y = A*x^2 + B*x + C
FUNCTION F_QuanDraticCalculate : lreal
VAR_INPUT
	A : LREAL;
	B : LREAL;
	C : LREAL;
	x : LREAL;
END_VAR
VAR_OUTPUT
	Y : LREAL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Y := A*x*x + B*x + C;
F_QuanDraticCalculate := Y;
]]></ST>
    </Implementation>
    <LineIds Name="F_QuanDraticCalculate">
      <LineId Id="7" Count="0" />
      <LineId Id="14" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>